title: Oracle Cloud Notes
description: A collection of notes for dealing with Oracle Cloud Infrastructure (OCI)
url: https://pythoncoderas.github.io/oracle-cloud-notes
theme: just-the-docs

search_enabled: true
